name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v3

      - run: echo "TEST_ROMS_SHA=$(curl https://api.github.com/repos/retrio/gb-test-roms/branches/master | jq -r ".commit.sha")" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
        with:
          repository: retrio/gb-test-roms
          path: test-roms
          sparse-checkout: |
            cpu_instrs/individual/
      - uses: actions/cache@v4
        with:
          path: test-roms
          key: ${{env.TEST_ROMS_SHA}}

      - run: |
          mkdir -p src/test/resources
          cp -vR test-roms/cpu_instrs/individual/*.gb src/test/resources/
          ls -lR
      - run: ./gradlew test