name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    env:
      REF: c240dd7d700e5c0b00a7bbba52b53e4ee67b5f15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v3

      - uses: actions/checkout@v4
        with:
          repository: retrio/gb-test-roms
          ref: ${{ env.REF }}
          path: test-roms
          sparse-checkout: |
            cpu_instrs/individual/
      - uses: actions/cache@v4
        with:
          path: test-roms
          key: key-${{ env.REF }}

      - run: |
          mkdir -p src/test/resources
          cp -vR test-roms/cpu_instrs/individual/*.gb src/test/resources/
      - run: ./gradlew test --info

      - uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: build/test-results/**/*.xml
          reporter: java-junit